version: "3.17"

tasks:
  install:
    desc: Install dependencies with pnpm
    cmds:
      - pnpm install

  build:
    desc: Build the bundled .gs file
    cmds:
      - pnpm run build

  test:
    desc: Run the Gleam test suite
    cmds:
      - gleam test

  format:
    desc: Gleam format
    cmds:
      - gleam format src test

  format.check:
    desc: Check Gleam formatting
    cmds:
      - gleam format --check src test
